sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t jonathankao97/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jonathankao97/docker-react npm run test -- --coverage